---
- hosts: webserver2
  become: yes
  vars:
    github_repo_url: "https://github.com/AGLoCo13/Node-React.js-Expenses-Application.git"
    project_directory: "/var/www/mern_app"
    pm2_app_name: "mern_app_backend"
  tasks:
    - name: Add Docker GPG key
      shell: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc

    - name: Add Docker repository to Apt sources
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update

    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Install Docker Compose
      command: >
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose
      become: yes
      become_user: root

    - name: Make Docker Compose executable
      file:
        path: /usr/local/bin/docker-compose
        mode: 'a+x'
      become: yes
      become_user: root

    - name: Clone the project repository from GitHub
      ansible.builtin.git:
        repo: "{{ github_repo_url }}"
        dest: "{{ project_directory }}"
        clone: yes
        update: yes
        force: yes

    - name: Build and Start Docker Compose
      command: docker-compose -f /var/www/mern_app/docker-compose.yml up -d
      become : yes